#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Try to load nvm only if it exists
export NVM_DIR="$HOME/.nvm"
if [ -s "$NVM_DIR/nvm.sh" ]; then
  . "$NVM_DIR/nvm.sh"
  nvm use default > /dev/null
fi

npx prettier $(git diff --name-only --cached --diff-filter=ACMR | sed 's| |\ |g') --write --ignore-unknown
# npm run lint # Uncomment this line to run linting before commit
npm test
# add changed files again
git add $(git diff --name-only --cached --diff-filter=ACMR)